const AppConfig = {
  project: {
    identiconOption: {
      margin: 0.3,
      size: 400,
    }
  },

  profile: {
    identiconOption: {
      margin: 0.25,
      size: 200,
    }
  },

  textEditor: {
    tinyMCEConfig: {
      height: 300,
      menubar: 'edit insert format',
      plugins: 'link bdesk_photo',
      toolbar: 'undo redo | bold italic underline | alignleft aligncenter alignright | outdent indent | bdesk_photo'
    }
  },

  button: {
    requestText: 'Requesting..',
  },

  postTypes: [
    'interview experience',
    'package',
    'referral',
    'inside',
  ],

  companyOptions: [
    'All',
    'Amazon',
    'Google',
    'Facebook',
    'Snapchat',
    'Uber',
    'Airbnb',
    'Dropbox',
    'Bloomberg',
    'Microsoft',
    'Twitter',
    'Palantir',
    'Coursera',
    'Databricks',
    'Pure Storage',
    'Two Sigma',
    'Square',
    'Quora',
    'MongoDB',
    '============',
    'eBay',
    'Squarespace',
    'Zillow',
    'Paypal',
    'Thumbtack',
    'NetApp',
    'Addepar',
    'Yahoo',
    'Rubrik',
    'Yelp',
    'Indeed',
    'Houzz',
    'SalesForce',
    'Factset',
    'TripAdvisor',
    'PoketGem',
    'Oracle',
    'VMWare',
    'Whitepages',
    'Grubhub',
    'Fidessa',
    'Udacity',
    'Tubular',
    'IXL Learning',
    'Qualtrics',
    'Stripe',
    'WeWork',
    'Adobe',
    'Tableau',
    'Plaid',
    'Wish',
    'Blend',
    'Medallia',
    'Yext',
    'Peak6',
    'IBM',
    'IMC',
    "==NEW=ADDED==",
    'EA',
    'BOA',
    'Blue Origin',
    'Intel',
    'AppDynamics',
    'Workday',
    'Oscar',
    'EMC',
    'Fitbit',
    'Factual',
    'GoDaddy',
    'MuleSoft',
    'Meraki',
    'Upstart',
    'FICO',
    'Affirm',
    'MemSQL',
    'Duolingo',
    'Sonos',
    'BirdEye',
    'GRAIL',
    'Hiya',
    'Dell',
    'Sift Science',
    'TubeMogul',
    'BetterJobs',
    'Granular',
    'ActionIQ',
    'BounceX',
    'Sensus',
    'Harris Corporation',
    'Xylem',
    'Netsmart',
    'Finicity',
    'OpenText',
    'Infor',
    '==TO=CHECK==',
    'Linkedin',
    'Credit Karma',
    'Expedia',
    'LiveRamp',
    'WePay',
    '=NOT=HIRING=',
    'Pinterster',
    'Atlassian',
    'Tinder',
    'Elementum',
    'Qumulo',
    'Cisco',
    'Audible',
    'Asana',
  ]
};

export default AppConfig;
